runtime: python39

# App Engine configuration for CloudFace AI
service: default

# Instance configuration
instance_class: F4_1G  # 1GB RAM, 600MHz CPU (sufficient for testing)
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

# Environment variables
env_variables:
  # Flask configuration
  FLASK_ENV: production
  
  # Google Cloud specific
  GAE_APPLICATION: your-project-id
  
  # Firebase configuration (use your existing values)
  GOOGLE_APPLICATION_CREDENTIALS: credentials/firebase-adminsdk.json
  
  # Add your other environment variables here
  # GOOGLE_CLIENT_ID: your-oauth-client-id
  # GOOGLE_CLIENT_SECRET: your-oauth-client-secret

# Static file handling
handlers:
- url: /static
  static_dir: static
  
- url: /favicon\.ico
  static_files: favicon.svg
  upload: favicon\.svg

- url: /.*
  script: auto
  secure: always

# Skip files (don't upload these)
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?tests/.*$
- ^(.*/)?test_.*\.py$
- node_modules/
- __pycache__/
- *.pyc
- backup_*/
- temp_processing_*.jpg

# Timeout settings
readiness_check:
  path: "/"
  check_interval_sec: 5
  timeout_sec: 4

liveness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 4
